### ISSUE TITLE
关于适配 Waline 评论系统那档事（英文水平不行，不编了）

### ISSUE THREAD

**Issue by gxres042** [Yuameshi/hexo-theme-mdx#2]
Hi,
I'm a Waline Comment user, and these days I saw this theme and very like it. But I found that it only support Gitalk, so I want to know when this theme will support Waline or not.
Thanks!

**Comment by yuameshi** [comment]
ok，我找个时间看看吧

**Comment by yuameshi** [comment]
而且一眼丁真鉴定为很多语法错误（

**Comment by gxres042** [comment]
> 而且一眼丁真鉴定为很多语法错误（

可想而知我的英语有多烂（

**Comment by yuameshi** [comment]
> > 而且一眼丁真鉴定为很多语法错误（
> 
> 可想而知我的英语有多烂（

那就乖乖zh-cn

**Comment by yuameshi** [comment]
啊，好烦，waline不同cdn的路径有点不一样，难顶

**Comment by gxres042** [comment]
hmm 太闲了，我 fork 一个看看研究一下

**Comment by gxres042** [comment]
我看了一下手册，写 comment.ejs 可能是这样的：

```
<div id="waline"></div>
<script src="https://cdn.bootcdn.net/ajax/libs/waline/2.6.1/waline.js"></script>
<link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/waline/2.6.1/waline.css" />
<script>
    Waline.init({
        el: '#waline',
        serverURL: '<%= theme.comment.waline.server_URL %>',
        lang: '<%= theme.comment.waline.lang %>',
        emoji: '<%= theme.comment.waline.emoji %>',
        dark: '<%= theme.comment.waline.dark %>',
        comment: '<%= theme.comment.waline.comment_count %>',
        path: '<%= theme.comment.waline.path %>'
        pageview: '<%= theme.comment.waline.page_view %>'
      });
</script>
```

**Comment by yuameshi** [comment]
我知道啊

**Comment by yuameshi** [comment]
现在难的只有多cdn适配了

**Comment by gxres042** [comment]
多 CDN 吗？我研究一下

**Comment by yuameshi** [comment]
我已经快了，今晚回家大概就行了

**Comment by yuameshi** [comment]
重构了一段代码

**Comment by yuameshi** [comment]
现在就还有staticfile和bytedance还不确定是否有walline

1826更新：staticfile似乎没有

**Comment by Yuameshi** [comment]
staticfile似乎没有

**Comment by gxres042** [comment]
> 现在就还有staticfile和bytedance还不确定是否有walline
> 
> 1826更新：staticfile似乎没有

https://cdn.bytedance.com/?query=waline&version=1.5.4

乐，staticfile 甚至连搜索都用不了

**Comment by yuameshi** [comment]
> > 现在就还有staticfile和bytedance还不确定是否有walline
> > 
> > 1826更新：staticfile似乎没有
> 
> https://cdn.bytedance.com/?query=waline&version=1.5.4
> 
> 乐，staticfile 甚至连搜索都用不了

看到了，但是v2没有，其他cdn都有v2了吧

**Comment by gxres042** [comment]
> > > 现在就还有staticfile和bytedance还不确定是否有walline
> > > 1826更新：staticfile似乎没有
> > 
> > 
> > https://cdn.bytedance.com/?query=waline&version=1.5.4
> > 乐，staticfile 甚至连搜索都用不了
> 
> 看到了，但是v2没有，其他cdn都有v2了吧

2022-03 上传的 1.5

这更新也太慢了吧（？

**Comment by yuameshi** [comment]
看了看staticfile的issue，发现检索系统是cdnjs的，推测staticfile和cdnjs是一个库

更新：已证实确实是

**Comment by gxres042** [comment]
> > > 现在就还有staticfile和bytedance还不确定是否有walline
> > > 1826更新：staticfile似乎没有
> > 
> > 
> > https://cdn.bytedance.com/?query=waline&version=1.5.4
> > 乐，staticfile 甚至连搜索都用不了
> 
> 看到了，但是v2没有，其他cdn都有v2了吧

刚刚去字节跳动 CDN 库看了一眼，要么 2021-08-03，要么 2022-03-01，绝了

**Comment by gxres042** [comment]
staticfile 在 2018 年就没有任何动静了，很多 2018 年之后的库，包括 Waline，也不会在里面了 🤔

**Comment by yuameshi** [comment]
> staticfile 在 2018 年就没有任何动静了，很多 2018 年之后的库，包括 Waline，也不会在里面了 🤔 

我看了，有，2.6.2也有
https://cdn.staticfile.org/waline/2.6.2/waline.js

![IMG_20220731_101320.jpg](https://user-images.githubusercontent.com/64469437/182006724-59a7d576-a787-434d-acdf-27dbb61ffd64.jpg)

**Comment by gxres042** [comment]
> > staticfile 在 2018 年就没有任何动静了，很多 2018 年之后的库，包括 Waline，也不会在里面了 🤔 
> 
> 我看了，有，2.6.2也有
> https://cdn.staticfile.org/waline/2.6.2/waline.js
> 
> ![IMG_20220731_101320.jpg](https://user-images.githubusercontent.com/64469437/182006724-59a7d576-a787-434d-acdf-27dbb61ffd64.jpg)

难怪怎么看到 staticfile 的主仓库在五月更新了一次
估计是网站没更新orz

**Comment by yuameshi** [comment]
有无时间给个serverUrl测试

**Comment by gxres042** [comment]
> 有无时间给个serverUrl测试

https://blog-waline.restent.win

**Comment by yuameshi** [comment]
> > 有无时间给个serverUrl测试
> 
> https://blog-waline.restent.win

ok

**Comment by yuameshi** [comment]
你可以拉取最新提交来测试@Restent

**Comment by gxres042** [comment]
> 你可以拉取最新提交来测试@Restent 

好，感谢

**Comment by gxres042** [comment]
@Yuameshi 测试过了，我这边 Waline 工作完全正常
Waline 可以 untest 转 stable 了
再次感谢wwww之前在 WordPress 的时候也是在用 MDx

**Comment by gxres042** [comment]
明天发 npm 包我再换上去，我比较喜欢 npm 安装主题（

**Comment by yuameshi** [comment]
okok

**Comment by yuameshi** [comment]
实话说我现在发包都行（

**Comment by Nofated095** [comment]
> 啊，好烦，waline不同cdn的路径有点不一样，难顶

可以细说一下吗
是指 <http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus用户指南-cdn提供商/index.html#JavaScript库CDN> 这种两种格式的路径吗

**Comment by yuameshi** [comment]
> > 啊，好烦，waline不同cdn的路径有点不一样，难顶
> 
> 可以细说一下吗 是指 [http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus用户指南-cdn提供商/index.html#JavaScript库CDN](http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-cdn%E6%8F%90%E4%BE%9B%E5%95%86/index.html#JavaScript%E5%BA%93CDN) 这种两种格式的路径吗

不确定，我指的是JSDelivr/Unpkg之类的包名是和npm一致（如`@waline/client`），而staticfile, bootcdn之类的就直接是包名(如`waline`)，另一个是JSDelivr和Unpkg的生产代码是在dist目录内的，而其他几家是直接放在根目录内的，详细可以看我代码

**Comment by yuameshi** [comment]
> 明天发 npm 包我再换上去，我比较喜欢 npm 安装主题（

npm包已经发布：[v0.5.1-alpha](https://www.npmjs.com/package/hexo-theme-mdx/v/0.5.1-alpha)

**Comment by Nofated095** [comment]
> > > 啊，好烦，waline不同cdn的路径有点不一样，难顶
> > 
> > 
> > 可以细说一下吗 是指 [http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus用户指南-cdn提供商/index.html#JavaScript库CDN](http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-cdn%E6%8F%90%E4%BE%9B%E5%95%86/index.html#JavaScript%E5%BA%93CDN) 这种两种格式的路径吗
> 
> 不确定，我指的是JSDelivr/Unpkg之类的包名是和npm一致（如`@waline/client`），而staticfile, bootcdn之类的就直接是包名(如`waline`)，另一个是JSDelivr和Unpkg的生产代码是在dist目录内的，而其他几家是直接放在根目录内的，详细可以看我代码

可以考虑分离出来 cdn 路径而不写死
类似于
<https://github.com/ppoffice/hexo-component-inferno/blob/master/src/hexo/helper/cdn.js>
<https://github.com/ppoffice/hexo-component-inferno/blob/master/src/hexo/helper/cdn.test.js>

**Comment by yuameshi** [comment]
> > > > 啊，好烦，waline不同cdn的路径有点不一样，难顶
> > > 
> > > 
> > > 可以细说一下吗 是指 [http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus用户指南-cdn提供商/index.html#JavaScript库CDN](http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-cdn%E6%8F%90%E4%BE%9B%E5%95%86/index.html#JavaScript%E5%BA%93CDN) 这种两种格式的路径吗
> > 
> > 不确定，我指的是JSDelivr/Unpkg之类的包名是和npm一致（如`@waline/client`），而staticfile, bootcdn之类的就直接是包名(如`waline`)，另一个是JSDelivr和Unpkg的生产代码是在dist目录内的，而其他几家是直接放在根目录内的，详细可以看我代码
> 
> 可以考虑分离出来 cdn 路径而不写死
> 类似于
> <https://github.com/ppoffice/hexo-component-inferno/blob/master/src/hexo/helper/cdn.js>
> <https://github.com/ppoffice/hexo-component-inferno/blob/master/src/hexo/helper/cdn.test.js>

如果我没理解错，我现在就是这样的：

https://github.com/Yuameshi/hexo-theme-mdx/blob/main/scripts/index.js
