### ISSUE TITLE
[Feature] 首页下头图部分显示 Slogan & 增加简洁页脚

### ISSUE THREAD

**Issue by gxres042** [Yuameshi/hexo-theme-mdx#4]
./layout/_partial/title.ejs

```
<div 
	class="pageTitle mdui-color-theme mdui-color-theme"
	id="pageTitleContainer"
	style="background-image: url('<%- props.background || theme.header_picture_link %>'); ">
	<% if (is_post() || is_page()) { %>
	    <h1 id="pageTitle">
		<%= props.title %>
	    </h1>
	<% } else { %>
	    <h1>
                <%= theme.subtitle %>
	     </h1>
	<% } %>
</div>
```

这样在非文章或页面的情况下在顶部显示 Slogan，而不是显示标题（左上角已经有标题显示了）

需要在主题的配置文件里增加一行 `slogan: ` 以便读取

已经在本地测试过，首页会显示 Slogan，进入文章后会显示标题。但我不确定其它环境是否如此。

麻烦了（

**Comment by gxres042** [comment]
~~发现问题了~~
~~它左上角的标题会跟着一起变，我看看怎么搞~~

好家伙，我在 Slogan 那一段多加了个 id="pageTitle"

**Comment by yuameshi** [comment]
我不太明白你的意思，能否使用图片方式描述一下，如果是类似`糸的窝 - SloganSloganSlogan` 我觉得莫得必要，侧边栏的about里有了

**Comment by gxres042** [comment]
> 我不太明白你的意思，能否使用图片方式描述一下，如果是类似`糸的窝 - SloganSloganSlogan` 我觉得莫得必要，侧边栏的about里有了

我自己的站已经修改好了，现在暂时不走 npm
https://blog.restent.win

**Comment by gxres042** [comment]
![屏幕截图 2022-08-26 092747](https://user-images.githubusercontent.com/53113178/186796991-f8badd12-0519-47ed-82a6-264383363180.jpg)

我给的设定是从 _config.yml 读取 subtitle 然后在这个头图位置显示

**Comment by gxres042** [comment]
![屏幕截图 2022-08-26 092931](https://user-images.githubusercontent.com/53113178/186797130-9a3a5b78-42bc-40fc-a208-700152b32793.jpg)

这个是我根据 WP MDx 默认页脚搞出来的，算是新增了一个可选的页脚

不过当时我写的时候没把在 config 里切换的写出来（第一条 if 语句就报错了）

**Comment by Yuameshi** [comment]
页脚切换可能得推，首页标语可以你提pr

**Comment by yuameshi** [comment]
页脚切换可能得推迟，首页标语可以你提pr

**Comment by yuameshi** [comment]
看看

**Comment by gxres042** [comment]
> 看看

我有时间拉下来看看

**Comment by gxres042** [comment]
标题是没有问题了
剩下那个页脚应该可以直接照搬我修的代码（
```
<footer class="footer mdui-text-color-theme-secondary">
	<div class="copyrights">
		<%- _p('footer.copyrights',`${theme.footer.since || (new Date()).getFullYear()} - ${(new Date()).getFullYear()} ${config.author}`) %>
	</div>
	</br>
	<div class="text">
	  <%-theme.footer.text%>
	  <% if (theme.footer.contact) { %>
		  <% if (theme.footer.contact && theme.footer.text) { %>
			  &nbsp;&nbsp;
		  <% } %>
		  <div class="contact">
			  <% for(el in theme.footer.contact){%>
				  <a href="<%= url_for(theme.footer.contact[el]) %>" class="mdui-text-color-theme-secondary">
					  <%=el%>
				  </a>
			  <%}%>
		  </div>
	  <% } %>
  </div>
  </br>
	<div class="footerLowerLayer" style="text-align: center;">
		<div class="center">
			<% if (theme.footer.hexo) { %>
				<a href="https://hexo.io" class="mdui-text-color-theme-secondary" target="_blank"><%- __('footer.hexo') %></a>
			<% } %>
			<% if (theme.footer.hexo && theme.footer.theme) { %>
				&nbsp;&&nbsp;
			<% } %>
			<% if (theme.footer.theme) { %>
				<a href="https://github.com/Yuameshi/hexo-theme-mdx" class="mdui-text-color-theme-secondary" target="_blank"><%- __('footer.theme') %></a>
			<% } %>
		</div>
	</div>
	<div class="footerLowerLayer">
		<div class="center">
			<% if (theme.footer.miit_icp) { %>
				<a href="https://beian.miit.gov.cn/" class="mdui-text-color-theme-secondary"><%= theme.footer.miit_icp %></a>
			<% } %>
			<% if (theme.footer.miit_icp && theme.footer.moe_icp) { %>
				&nbsp;/&nbsp;
			<% } %>
			<% if (theme.footer.moe_icp) { %>
				<a href="https://icp.gov.moe/?keyword=<%= theme.footer.moe_icp %>" class="mdui-text-color-theme-secondary">萌ICP备<%= theme.footer.moe_icp %>号</a>
			<% } %>
		</div>
	</div>
</footer>
```

**Comment by gxres042** [comment]
说实在我想吐槽个东西
就是头图部分的文字跟随 MDUI 主题的话，我两个站设置的颜色基本都是黑字，搞得我必须修代码设白

**Comment by gxres042** [comment]
等会，按现在这样主页下滑左上角直接 Slogan
我觉得应该是这样写的：
```
	<% if (is_home()) { %>
		<h1>
			<%= title %>
		</h1>
	<% } else { %>
		<h1 id="pageTitle">
			<%= title %>
		</h1>
	<% } %>
```
多加一个 is_home() 的判定，在主页就没必要左上角 Slogan 了（

**Comment by yuameshi** [comment]
> 说实在我想吐槽个东西 就是头图部分的文字跟随 MDUI 主题的话，我两个站设置的颜色基本都是黑字，搞得我必须修代码设白

原版也是这样（？

**Comment by yuameshi** [comment]
> 等会，按现在这样主页下滑左上角直接 Slogan 我觉得应该是这样写的：
> 
> ```
> 	<% if (is_home()) { %>
> 		<h1>
> 			<%= title %>
> 		</h1>
> 	<% } else { %>
> 		<h1 id="pageTitle">
> 			<%= title %>
> 		</h1>
> 	<% } %>
> ```
> 
> 多加一个 is_home() 的判定，在主页就没必要左上角 Slogan 了（

smj8左上角不是显示网站标题吗

**Comment by gxres042** [comment]
> > 等会，按现在这样主页下滑左上角直接 Slogan 我觉得应该是这样写的：
> > ```
> > 	<% if (is_home()) { %>
> > 		<h1>
> > 			<%= title %>
> > 		</h1>
> > 	<% } else { %>
> > 		<h1 id="pageTitle">
> > 			<%= title %>
> > 		</h1>
> > 	<% } %>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 多加一个 is_home() 的判定，在主页就没必要左上角 Slogan 了（
> 
> smj8左上角不是显示网站标题吗

有没有一种可能，我测试的时候，首页往下滑，左上角直接显示 Slogan（痴呆

```
	<% if (is_home()) { %>
		<h1>
			<%= title %>
		</h1>
	<% } else { %>
```

所以为什么我要把 h1 的 id=pageTitle 给摘掉

**Comment by gxres042** [comment]
> > 说实在我想吐槽个东西 就是头图部分的文字跟随 MDUI 主题的话，我两个站设置的颜色基本都是黑字，搞得我必须修代码设白
> 
> 原版也是这样（？

那我自用版火速把它改掉（

**Comment by gxres042** [comment]
> > > 等会，按现在这样主页下滑左上角直接 Slogan 我觉得应该是这样写的：
> > > ```
> > > 	<% if (is_home()) { %>
> > > 		<h1>
> > > 			<%= title %>
> > > 		</h1>
> > > 	<% } else { %>
> > > 		<h1 id="pageTitle">
> > > 			<%= title %>
> > > 		</h1>
> > > 	<% } %>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 多加一个 is_home() 的判定，在主页就没必要左上角 Slogan 了（
> > 
> > 
> > smj8左上角不是显示网站标题吗
> 
> 有没有一种可能，我测试的时候，首页往下滑，左上角直接显示 Slogan（痴呆
> 
> ```
> 	<% if (is_home()) { %>
> 		<h1>
> 			<%= title %>
> 		</h1>
> 	<% } else { %>
> ```
> 
> 所以为什么我要把 h1 的 id=pageTitle 给摘掉

id=pageTitle 会读取 <%= title %>，滑下去的话左上角那个位置直接变成 title，给整不会了

**Comment by yuameshi** [comment]
> > > 等会，按现在这样主页下滑左上角直接 Slogan 我觉得应该是这样写的：
> > > ```
> > > 	<% if (is_home()) { %>
> > > 		<h1>
> > > 			<%= title %>
> > > 		</h1>
> > > 	<% } else { %>
> > > 		<h1 id="pageTitle">
> > > 			<%= title %>
> > > 		</h1>
> > > 	<% } %>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 多加一个 is_home() 的判定，在主页就没必要左上角 Slogan 了（
> > 
> > smj8左上角不是显示网站标题吗
> 
> 有没有一种可能，我测试的时候，首页往下滑，左上角直接显示 Slogan（痴呆
> 
> ```
> 	<% if (is_home()) { %>
> 		<h1>
> 			<%= title %>
> 		</h1>
> 	<% } else { %>
> ```
> 
> 所以为什么我要把 h1 的 id=pageTitle 给摘掉

你的问题不要找我.jpg

我的代码里是根本没有select这个pageTitle，战未来而已hhh

**Comment by gxres042** [comment]
> > > > 等会，按现在这样主页下滑左上角直接 Slogan 我觉得应该是这样写的：
> > > > ```
> > > > 	<% if (is_home()) { %>
> > > > 		<h1>
> > > > 			<%= title %>
> > > > 		</h1>
> > > > 	<% } else { %>
> > > > 		<h1 id="pageTitle">
> > > > 			<%= title %>
> > > > 		</h1>
> > > > 	<% } %>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 多加一个 is_home() 的判定，在主页就没必要左上角 Slogan 了（
> > > 
> > > 
> > > smj8左上角不是显示网站标题吗
> > 
> > 
> > 有没有一种可能，我测试的时候，首页往下滑，左上角直接显示 Slogan（痴呆
> > ```
> > 	<% if (is_home()) { %>
> > 		<h1>
> > 			<%= title %>
> > 		</h1>
> > 	<% } else { %>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 所以为什么我要把 h1 的 id=pageTitle 给摘掉
> 
> 你的问题不要找我.jpg
> 
> 我的代码里是根本没有select这个pageTitle，战未来而已hhh

不管了，怎么样就怎么样吧

反正我这边已经修好了）

**Comment by yuameshi** [comment]
我好像明白了，我回头看看（

**Comment by yuameshi** [comment]
其实，这个页脚叫做传统（

**Comment by yuameshi** [comment]
简洁是这样的
![image](https://user-images.githubusercontent.com/64469437/198497207-9abfa899-742e-4b81-b9f0-9145d022c2b0.png)
![image](https://user-images.githubusercontent.com/64469437/198497265-36143ac4-0912-417e-9266-f0134d6ad2d5.png)

**Comment by gxres042** [comment]
> 简洁是这样的 ![image](https://user-images.githubusercontent.com/64469437/198497207-9abfa899-742e-4b81-b9f0-9145d022c2b0.png) ![image](https://user-images.githubusercontent.com/64469437/198497265-36143ac4-0912-417e-9266-f0134d6ad2d5.png)

也可以

**Comment by yuameshi** [comment]
可以看看新版

**Comment by yuameshi** [comment]
此Issue将在两个月后Lock
